backend:
  name: github
  repo: jsadler-angry/gatsby-starter-default

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - file: "content/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro text, name: intro, widget: text }
          - { label: Image, name: image, widget: image }
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro text, name: intro, widget: text }
          - { label: Image, name: image, widget: image }
      - file: "content/team.md"
        label: "Team Page"
        name: "team"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
